name: ml-example-project-wandb
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - make
  - pip
  - pandas
  - scikit-learn
  - matplotlib
  - scikit-plot
  - jupyter
  - pyarrow
  - seaborn
  - pip:
    - click
    - python-dotenv
    - rich
    - pandera
    - evidently
    - wandb