main:
  project_name: housing-model
  experiment_name: dev
evaluation:
  validation_set_ratio = 0.2
  default_model_config = "src.models.model_configs.prod_model_config"
  cross_valTARGET_COLUMNidation_folds = 5
  target_column = "median_house_price"
ridge_pipeline:
  regressor__alpha: 2
random_forest_pipeline:
  regressor__max_depth: 10

