FROM continuumio/miniconda3

WORKDIR /mlops-example

# Create the environment:
COPY conda.yml .
RUN conda env create -f conda.yml

# Copy main
COPY src ./src
COPY conf ./conf
COPY setup.py .
COPY Makefile .


# Make sure the conda environment is activated when running a container
RUN echo "conda activate ml-example-project-wandb" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

# Install main
RUN conda activate ml-example-main-wandb
RUN pip install -e .