defaults:
  - main: training-pipeline
  - model: random_forest
  - evaluation: training-pipeline
  - artifacts: training-pipeline
  - override /hydra/job_logging: null

hydra:
  output_subdir: null
  run:
    dir: .